version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: systeminstaller-keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin123
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HTTP_ENABLED=true
      - KC_HEALTH_ENABLED=true
    ports:
      - "8082:8080"
    networks:
      - systeminstaller-net
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    command: start-dev --import-realm
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/localhost/8080 && echo -e 'GET /health/ready HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n' >&3 && cat <&3 | grep -q '200 OK'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    container_name: systeminstaller-gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8090
      - Keycloak__Authority=http://keycloak:8082
      - Keycloak__Realm=systeminstaller
      - Keycloak__ClientId=systeminstaller-client
      - Keycloak__ClientSecret=development-secret
    ports:
      - "8090:8090"
    depends_on:
      keycloak:
        condition: service_healthy
    networks:
      - systeminstaller-net

  web:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: systeminstaller-web
    ports:
      - "3000:8080"
    depends_on:
      - gateway
    networks:
      - systeminstaller-net

networks:
  systeminstaller-net:
    driver: bridge
