version: '3.8'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: systeminstaller-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    networks:
      - systeminstaller-net
    healthcheck:
      test: ["CMD-SHELL", "pidof sqlservr || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: systeminstaller-keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin123
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HTTP_ENABLED=true
      - KC_HEALTH_ENABLED=true
    ports:
      - "8080:8080"
    networks:
      - systeminstaller-net
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    command: start-dev --import-realm
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/localhost/8080 && echo -e 'GET /health/ready HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n' >&3 && cat <&3 | grep -q '200 OK'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  web:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: systeminstaller-web
    ports:
      - "3000:8080"
    depends_on:
      - api
    networks:
      - systeminstaller-net

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: systeminstaller-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Server=db;Database=SystemInstallerDb;User=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
      - Authentication__Keycloak__Authority=http://keycloak:8080/realms/systeminstaller
      - Authentication__Keycloak__ClientId=systeminstaller-web
      - Authentication__Keycloak__ClientSecret=your-client-secret
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    networks:
      - systeminstaller-net

networks:
  systeminstaller-net:
    driver: bridge
