version: '3.8'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: systeminstaller-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    networks:
      - systeminstaller-net
    healthcheck:
      test: ["CMD-SHELL", "pidof sqlservr || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: systeminstaller-web
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=SystemInstallerDb;User=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - systeminstaller-net

networks:
  systeminstaller-net:
    driver: bridge
